    -- Generated from iso4217_active.csv
-- Flyway *repeatable* migration (R__*.sql). Idempotent via ON CONFLICT.
--
-- Expected schema (minimal):
--   CREATE TABLE currencies (
--     code CHAR(3) PRIMARY KEY,
--     name TEXT NOT NULL,
--     decimal_scale SMALLINT NOT NULL,
--     active BOOLEAN NOT NULL DEFAULT TRUE
--   );

INSERT INTO currencies (code, name, decimal_scale, active) VALUES
  ('AED', 'United Arab Emirates Dirham', 2, TRUE),
  ('AFN', 'Afghan Afghani', 0, TRUE),
  ('ALL', 'Albanian Lek', 0, TRUE),
  ('AMD', 'Armenian Dram', 2, TRUE),
  ('ANG', 'Netherlands Antillean Guilder', 2, TRUE),
  ('AOA', 'Angolan Kwanza', 2, TRUE),
  ('ARS', 'Argentine Peso', 2, TRUE),
  ('AUD', 'Australian Dollar', 2, TRUE),
  ('AWG', 'Aruban Florin', 2, TRUE),
  ('AZN', 'Azerbaijani Manat', 2, TRUE),
  ('BAM', 'Bosnia-Herzegovina Convertible Mark', 2, TRUE),
  ('BBD', 'Barbadian Dollar', 2, TRUE),
  ('BDT', 'Bangladeshi Taka', 2, TRUE),
  ('BGN', 'Bulgarian Lev', 2, TRUE),
  ('BHD', 'Bahraini Dinar', 3, TRUE),
  ('BIF', 'Burundian Franc', 0, TRUE),
  ('BMD', 'Bermudan Dollar', 2, TRUE),
  ('BND', 'Brunei Dollar', 2, TRUE),
  ('BOB', 'Bolivian Boliviano', 2, TRUE),
  ('BOV', 'Bolivian Mvdol', 2, TRUE),
  ('BRL', 'Brazilian Real', 2, TRUE),
  ('BSD', 'Bahamian Dollar', 2, TRUE),
  ('BTN', 'Bhutanese Ngultrum', 2, TRUE),
  ('BWP', 'Botswanan Pula', 2, TRUE),
  ('BYN', 'Belarusian Ruble', 2, TRUE),
  ('BZD', 'Belize Dollar', 2, TRUE),
  ('CAD', 'Canadian Dollar', 2, TRUE),
  ('CDF', 'Congolese Franc', 2, TRUE),
  ('CHE', 'WIR Euro', 2, TRUE),
  ('CHF', 'Swiss Franc', 2, TRUE),
  ('CHW', 'WIR Franc', 2, TRUE),
  ('CLF', 'Chilean Unit of Account (UF)', 4, TRUE),
  ('CLP', 'Chilean Peso', 0, TRUE),
  ('CNH', 'Chinese Yuan (offshore)', 2, TRUE),
  ('CNY', 'Chinese Yuan', 2, TRUE),
  ('COP', 'Colombian Peso', 2, TRUE),
  ('COU', 'Colombian Real Value Unit', 2, TRUE),
  ('CRC', 'Costa Rican Colón', 2, TRUE),
  ('CUC', 'Cuban Convertible Peso', 2, TRUE),
  ('CUP', 'Cuban Peso', 2, TRUE),
  ('CVE', 'Cape Verdean Escudo', 2, TRUE),
  ('CZK', 'Czech Koruna', 2, TRUE),
  ('DJF', 'Djiboutian Franc', 0, TRUE),
  ('DKK', 'Danish Krone', 2, TRUE),
  ('DOP', 'Dominican Peso', 2, TRUE),
  ('DZD', 'Algerian Dinar', 2, TRUE),
  ('EGP', 'Egyptian Pound', 2, TRUE),
  ('ERN', 'Eritrean Nakfa', 2, TRUE),
  ('ETB', 'Ethiopian Birr', 2, TRUE),
  ('EUR', 'Euro', 2, TRUE),
  ('FJD', 'Fijian Dollar', 2, TRUE),
  ('FKP', 'Falkland Islands Pound', 2, TRUE),
  ('GBP', 'British Pound', 2, TRUE),
  ('GEL', 'Georgian Lari', 2, TRUE),
  ('GHS', 'Ghanaian Cedi', 2, TRUE),
  ('GIP', 'Gibraltar Pound', 2, TRUE),
  ('GMD', 'Gambian Dalasi', 2, TRUE),
  ('GNF', 'Guinean Franc', 0, TRUE),
  ('GTQ', 'Guatemalan Quetzal', 2, TRUE),
  ('GYD', 'Guyanaese Dollar', 2, TRUE),
  ('HKD', 'Hong Kong Dollar', 2, TRUE),
  ('HNL', 'Honduran Lempira', 2, TRUE),
  ('HRK', 'Croatian Kuna', 2, TRUE),
  ('HTG', 'Haitian Gourde', 2, TRUE),
  ('HUF', 'Hungarian Forint', 2, TRUE),
  ('IDR', 'Indonesian Rupiah', 2, TRUE),
  ('ILS', 'Israeli New Shekel', 2, TRUE),
  ('INR', 'Indian Rupee', 2, TRUE),
  ('IQD', 'Iraqi Dinar', 0, TRUE),
  ('IRR', 'Iranian Rial', 0, TRUE),
  ('ISK', 'Icelandic Króna', 0, TRUE),
  ('JMD', 'Jamaican Dollar', 2, TRUE),
  ('JOD', 'Jordanian Dinar', 3, TRUE),
  ('JPY', 'Japanese Yen', 0, TRUE),
  ('KES', 'Kenyan Shilling', 2, TRUE),
  ('KGS', 'Kyrgystani Som', 2, TRUE),
  ('KHR', 'Cambodian Riel', 2, TRUE),
  ('KMF', 'Comorian Franc', 0, TRUE),
  ('KPW', 'North Korean Won', 0, TRUE),
  ('KRW', 'South Korean Won', 0, TRUE),
  ('KWD', 'Kuwaiti Dinar', 3, TRUE),
  ('KYD', 'Cayman Islands Dollar', 2, TRUE),
  ('KZT', 'Kazakhstani Tenge', 2, TRUE),
  ('LAK', 'Laotian Kip', 0, TRUE),
  ('LBP', 'Lebanese Pound', 0, TRUE),
  ('LKR', 'Sri Lankan Rupee', 2, TRUE),
  ('LRD', 'Liberian Dollar', 2, TRUE),
  ('LSL', 'Lesotho Loti', 2, TRUE),
  ('LYD', 'Libyan Dinar', 3, TRUE),
  ('MAD', 'Moroccan Dirham', 2, TRUE),
  ('MDL', 'Moldovan Leu', 2, TRUE),
  ('MGA', 'Malagasy Ariary', 0, TRUE),
  ('MKD', 'Macedonian Denar', 2, TRUE),
  ('MMK', 'Myanmar Kyat', 0, TRUE),
  ('MNT', 'Mongolian Tugrik', 2, TRUE),
  ('MOP', 'Macanese Pataca', 2, TRUE),
  ('MRU', 'Mauritanian Ouguiya', 2, TRUE),
  ('MUR', 'Mauritian Rupee', 2, TRUE),
  ('MVR', 'Maldivian Rufiyaa', 2, TRUE),
  ('MWK', 'Malawian Kwacha', 2, TRUE),
  ('MXN', 'Mexican Peso', 2, TRUE),
  ('MXV', 'Mexican Investment Unit', 2, TRUE),
  ('MYR', 'Malaysian Ringgit', 2, TRUE),
  ('MZN', 'Mozambican Metical', 2, TRUE),
  ('NAD', 'Namibian Dollar', 2, TRUE),
  ('NGN', 'Nigerian Naira', 2, TRUE),
  ('NIO', 'Nicaraguan Córdoba', 2, TRUE),
  ('NOK', 'Norwegian Krone', 2, TRUE),
  ('NPR', 'Nepalese Rupee', 2, TRUE),
  ('NZD', 'New Zealand Dollar', 2, TRUE),
  ('OMR', 'Omani Rial', 3, TRUE),
  ('PAB', 'Panamanian Balboa', 2, TRUE),
  ('PEN', 'Peruvian Sol', 2, TRUE),
  ('PGK', 'Papua New Guinean Kina', 2, TRUE),
  ('PHP', 'Philippine Piso', 2, TRUE),
  ('PKR', 'Pakistani Rupee', 2, TRUE),
  ('PLN', 'Polish Zloty', 2, TRUE),
  ('PYG', 'Paraguayan Guarani', 0, TRUE),
  ('QAR', 'Qatari Rial', 2, TRUE),
  ('RON', 'Romanian Leu', 2, TRUE),
  ('RSD', 'Serbian Dinar', 0, TRUE),
  ('RUB', 'Russian Ruble', 2, TRUE),
  ('RWF', 'Rwandan Franc', 0, TRUE),
  ('SAR', 'Saudi Riyal', 2, TRUE),
  ('SBD', 'Solomon Islands Dollar', 2, TRUE),
  ('SCR', 'Seychellois Rupee', 2, TRUE),
  ('SDG', 'Sudanese Pound', 2, TRUE),
  ('SEK', 'Swedish Krona', 2, TRUE),
  ('SGD', 'Singapore Dollar', 2, TRUE),
  ('SHP', 'St. Helena Pound', 2, TRUE),
  ('SLL', 'Sierra Leonean Leone', 0, TRUE),
  ('SOS', 'Somali Shilling', 0, TRUE),
  ('SRD', 'Surinamese Dollar', 2, TRUE),
  ('SSP', 'South Sudanese Pound', 2, TRUE),
  ('STN', 'São Tomé & Príncipe Dobra', 2, TRUE),
  ('SYP', 'Syrian Pound', 0, TRUE),
  ('SZL', 'Swazi Lilangeni', 2, TRUE),
  ('THB', 'Thai Baht', 2, TRUE),
  ('TJS', 'Tajikistani Somoni', 2, TRUE),
  ('TMT', 'Turkmenistani Manat', 2, TRUE),
  ('TND', 'Tunisian Dinar', 3, TRUE),
  ('TOP', 'Tongan Paʻanga', 2, TRUE),
  ('TRY', 'Turkish Lira', 2, TRUE),
  ('TTD', 'Trinidad & Tobago Dollar', 2, TRUE),
  ('TWD', 'New Taiwan Dollar', 2, TRUE),
  ('TZS', 'Tanzanian Shilling', 2, TRUE),
  ('UAH', 'Ukrainian Hryvnia', 2, TRUE),
  ('UGX', 'Ugandan Shilling', 0, TRUE),
  ('USD', 'US Dollar', 2, TRUE),
  ('USN', 'US Dollar (Next day)', 2, TRUE),
  ('UYI', 'Uruguayan Peso (Indexed Units)', 0, TRUE),
  ('UYU', 'Uruguayan Peso', 2, TRUE),
  ('UYW', 'Uruguayan Nominal Wage Index Unit', 4, TRUE),
  ('UZS', 'Uzbekistani Som', 2, TRUE),
  ('VES', 'Venezuelan Bolívar', 2, TRUE),
  ('VND', 'Vietnamese Dong', 0, TRUE),
  ('VUV', 'Vanuatu Vatu', 0, TRUE),
  ('WST', 'Samoan Tala', 2, TRUE),
  ('XAF', 'Central African CFA Franc', 0, TRUE),
  ('XAG', 'Silver', 2, TRUE),
  ('XAU', 'Gold', 2, TRUE),
  ('XBA', 'European Composite Unit', 2, TRUE),
  ('XBB', 'European Monetary Unit', 2, TRUE),
  ('XBC', 'European Unit of Account (XBC)', 2, TRUE),
  ('XBD', 'European Unit of Account (XBD)', 2, TRUE),
  ('XCD', 'East Caribbean Dollar', 2, TRUE),
  ('XDR', 'Special Drawing Rights', 2, TRUE),
  ('XOF', 'West African CFA Franc', 0, TRUE),
  ('XPD', 'Palladium', 2, TRUE),
  ('XPF', 'CFP Franc', 0, TRUE),
  ('XPT', 'Platinum', 2, TRUE),
  ('XSU', 'Sucre', 2, TRUE),
  ('XTS', 'Testing Currency Code', 2, TRUE),
  ('XUA', 'ADB Unit of Account', 2, TRUE),
  ('XXX', 'Unknown Currency', 2, TRUE),
  ('YER', 'Yemeni Rial', 0, TRUE),
  ('ZAR', 'South African Rand', 2, TRUE),
  ('ZMW', 'Zambian Kwacha', 2, TRUE)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  decimal_scale = EXCLUDED.decimal_scale,
  active = EXCLUDED.active;
